python3 main.py --data_index 0
python3 main.py --data_index 1
python3 main.py --data_index 2
python3 main.py --data_index 3
python3 main.py --data_index 4
python3 main.py --data_index 5
python3 main.py --data_index 6
python3 main.py --data_index 7
python3 main.py --data_index 8
python3 main.py --data_index 9
python3 main.py --data_index 10
python3 main.py --data_index 11
python3 main.py --data_index 12
python3 main.py --data_index 13
python3 main.py --data_index 14
python3 main.py --data_index 15
python3 main.py --data_index 16
python3 main.py --data_index 17
python3 main.py --data_index 18
python3 main.py --data_index 19
python3 main.py --data_index 20
python3 main.py --data_index 21
python3 main.py --data_index 22
python3 main.py --data_index 23
python3 main.py --data_index 24
